
title: "Bradley S. Harris"
description: "Academic Homepage | CV | Research"
url: "https://bradsharris.github.io" 

# Author settings
author:
  name: "Bradley S. Harris"
  avatar: "/assets/images/avatar.jpg" # optional photo
  bio: "Postdoctoral Research Associate"
  location: "Richland WA, USA"
  email: "bradscottharris@gmail.com"
  links:
    - label: "CV"
      icon: "fas fa-file-alt"
      url: "/assets/CV.pdf"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=fwNmhaEAAAAJ&hl=en"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0001-9704-4656"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bradsharris"

# Theme settings
remote_theme: mmistakes/minimal-mistakes

# Plugins (required by Minimal Mistakes)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Layout and Navigation
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/assets/CV.pdf"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Contact"
    url: "/contact/"

# Optional features
markdown: kramdown
kramdown:
  input: GFM
